Fix missing cli
eclipse-velocitas/pkg-velocitas-uprotocol pull request #6
Opened 2024-04-12 16:54 UTC by doosuu

Fixes handling of devContainers which do not ship with Velocitas CLI pre installed (update fails due to the initial version check erroring out)

2024-04-13 17:35 UTC, dennismeister93 requested changes

2024-04-13 17:35 UTC, dennismeister93 commented on components/extensions/devcontainer-setup-java/src/.devcontainer/scripts/setup_codespaces.sh
> +fi
missing EOL

2024-04-14 12:48 UTC, doosuu commented on components/extensions/devcontainer-setup-java/src/.devcontainer/scripts/setup_codespaces.sh
> +fi
Done

2024-04-15 07:35 UTC, dennismeister93 approved these changes
lgtm

2024-04-15 08:37 UTC, merged